server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848 # nacos服务注册中心
    sentinel:
      transport:
        dashboard: 192.168.56.101:8858 # 配置sentinel dashboard
        port: 8719 # 默认是8719端口,假如被占用会自动从8719开始依次+1扫描,直到找到未被占用的端口
#      datasource:
#        dsl:
#          nacos:
#            server-addr: 192.168.56.101:8848
#            data-id: cloudalibaba-sentinel-service
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'