server:
  port: 8000
eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka/
ribbon:
  ReadTimeout:  4000 #指建立链接所需要的时间
  ConnectTimeout: 1000 #指建立链接后获取资源所需要的时间
spring:
  application:
    name: cloud-consumer-hystrix-order
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。 