server:
  port: 8000
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 192.168.56.101
      port: 8500
      discovery:
        service-name: ${spring.application.name} 