server:
  port: 8080
spring:
  application:
    name: springboot-redis
  redis:
    database: 0 # redis数据库索引(默认为0)
    host: 127.0.0.1
    port: 6379
    password: huanglin233
    jedis:
      pool:
        max-active: 200 # 最大链接数,负数没有限制
        max-wait: -1 # 最大阻塞链接时间,负数表示没有限制
        max-idle: 10 # 最大空闲链接
        min-idle: 0 # 最小空闲链接
    timeout: 1000 # 链接超时时间(毫秒)
