server:
  port: 2003
spring:
  application:
    name: seata-account-service
  cloud:
#    alibaba:
#      seata:
#        tx-service-group: hl_cloud_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seata_account?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: root

seata:
  tx-service-group: order
  enabled: true
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      order: default
    grouplist:
      default: 127.0.0.1:8091

feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata : info

mybatis:
  mapper-locations: classpath*:mapper/*.xml