server:
  port: 8004
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.56.101
      port: 8500
      discovery:
        service-name: ${spring.application.name} 