server:
  port: 8080 
spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: hl
    password: hl
    virtual-host: my_vhost
    # ------- 消息确认配置项 --------
    # 确认消息已发送到交换机
#    publisher-confirms: true 高版本使用一下参数
    publisher-confirm-type: correlated
    # 确认消息已发送队列
    publisher-returns: true