server:
  port: 8080
spring:
  application:
    name: springboot-kafka
  kafka:
    bootstrap-servers:
    - 172.17.0.1:9092
    # producer相关配置
    producer:
      retries: 0
      # 每次批量发送消息的数量
      acks: all
      batch-size: 16384
      buffer-memory: 33554432
      # 指定key和value的编码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # consumer 相关配置
    consumer:
      group-id: test
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 1000
      # 指定key和value的解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    streams:
      application-id: test-kafka-stream # 默认取springboot应用名
      bootstrap-servers: 172.17.0.1:9092 # 会覆盖 spring.kafka.bootstrap-servers 配置
#      auto-startup: true
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde # 序列化key
          value:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde # 序列化value
          timestamp:
            extractor: org.apache.kafka.streams.processor.WallclockTimestampExtractor
#        spring:
#          json:
#            trusted:
#              packages: com.hl.*

logging:
        level:
            ROOT: INFO
            org.springframework.kafka: ERROR